---
abstract: 'Beacon files as source for SeeAlso::Server'
author:
  - 'Thomas Berger <ThB@gymel.com>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3613'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SeeAlso-Source-BeaconAggregator
provides:
  SeeAlso::Source::BeaconAggregator:
    file: lib/SeeAlso/Source/BeaconAggregator.pm
    version: 0.2
  SeeAlso::Source::BeaconAggregator::Maintenance:
    file: lib/SeeAlso/Source/BeaconAggregator/Maintenance.pm
    version: 0.2
  SeeAlso::Source::BeaconAggregator::Publisher:
    file: lib/SeeAlso/Source/BeaconAggregator/Publisher.pm
    version: 0.2
recommends:
  Getopt::Long: 0
  LWP: 5.827
  Pod::Usage: 0
  SeeAlso::Server: 0.58
requires:
  CGI: 3.0
  Carp: 0
  DBD::SQLite: 1.25
  DBI: 1.6
  File::Temp: 0
  HTTP::Date: 5.0
  HTTP::Request: 5.0
  SeeAlso::Identifier: 0.46
  SeeAlso::Identifier::GND: 0.54
  SeeAlso::Server: 0.57
  perl: v5.8.2
resources:
  license: http://dev.perl.org/licenses/
version: 0.2
